[workspace]
resolver = "2" # Important! wgpu/Bevy needs this!
members = [
    "simple-arcade",
    "arcade-util",
    "arcade-menu",
    "arcade-result",
    "snake",
    "minesweeper",
]

[workspace.dependencies]
bevy = { version = "0.10", features = ["dynamic_linking"] }
